### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by cybvitthal** [martijn00/AndroidSlidingUpPanelXamarin#4]
Library still uses Xamarin.Android.Support.v4 (>= 26.0.2) and Xamarin.Android.Support.v7.RecyclerView.
Do you plan to migrate to AndroidX

**Comment by martijn00** [comment]
Can you open a PR?

**Comment by cybvitthal** [comment]
As this is binding library, we need to check for migrated Jar, right?

**Comment by cybvitthal** [comment]
Hey,
Let me know, the go ahead for the AndroidX migration, thanks.

**Comment by martijn00** [comment]
Yeah off course! Go ahead and make the PR!

**Comment by cybvitthal** [comment]
Yeah, but, we need .aar migrated to AndroidX, right?
Otherwise, I don't think this library can be migrated or maintained further.

**Comment by cybvitthal** [comment]
Let me know, if you have some idea, Thanks!

**Comment by martijn00** [comment]
Yes it is a breaking change. It needs to go to AndroidX

**Comment by cybvitthal** [comment]
But, how a binding library can me migrated. We have no access to the code here.

**Comment by cybvitthal** [comment]
I see 2 options here:
Utilize https://github.com/hannesa2/AndroidSlidingUpPanel to create Xamarin Binding.
OR
Migrate https://github.com/umano/AndroidSlidingUpPanel to AndroidX and create Xamarin Binding

**Comment by cybvitthal** [comment]
Created https://github.com/vitthal-patil/AndroidXSlidingUpPanelXamarin, just in case.
